default_language_version:
    python: python3.9

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^src/|^tests/
      - id: ruff-format
        files: ^src/|^tests/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: ["--check"]
        files: ^src/|^tests/

  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: bash -c 'cd $(git rev-parse --show-toplevel)/orchestrator && poetry run pytest'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
