name: Publish Python 🐍 distribution 📦 to GitHub Packages

on:
  workflow_run:
    workflows: ["Release & Publish"]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install python-semantic-release

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false
        poetry config repositories.github https://github.com/j-raghavan/orchestrator/releases/download/latest/
        poetry config http-basic.github ${{ github.repository_owner }} ${{ secrets.GITHUB_TOKEN }}

    - name: Semantic Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        python -m semantic_release publish

    - name: Build package
      run: poetry build

    - name: Publish to GitHub Packages
      run: poetry publish -r github
